@startuml Seq_QuanLyTaiKhoan
autonumber "<b>##."
skinparam sequenceMessageAlign center
skinparam style strictuml

actor "Ban tổ chức" as BTC
boundary "QuanLyTaiKhoanForm" as UI
control "TaiKhoanController" as SYS
entity ": TAIKHOAN" as DB

BTC -> UI: Chọn chức năng "Quản lý tài khoản"
activate UI

UI -> SYS: Yêu cầu lấy danh sách tài khoản
deactivate UI
activate SYS

SYS -> DB: Select danh sách tài khoản
activate DB
DB --> SYS: Trả về danh sách 
deactivate DB

SYS --> UI: Trả về dữ liệu và render UI
deactivate SYS
activate UI
UI -> UI: Hiển thị danh sách tài khoản
deactivate UI

@enduml